[project]
name = "soyml"
version = "0.3.1"
requires-python = ">=3.12,<3.15"
dependencies = [
    "minlog>=0.6.0,<1.0.0",
    "numpy>=2.4.0,<3.0.0",
    "onnx>=1.20.0,<2.0.0",
]

[project.optional-dependencies]
ort = ["onnxruntime>=1.23.2,<2.0.0"]
wonnx = ["wonnx>=0.5.0,<1.0.0"]
ncnn = ["ncnn>=1.0.0"]
torch = ["torch", "torchinfo>=1.8.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
